### ISSUE TITLE
Mobile Tile Rooted dja0231

### ISSUE THREAD

**Issue by Bushy2022** [seud0nym/tch-gui-unhide#100]
The Mobile tile is not visible although it has been selected under management tile

**Comment by seud0nym** [comment]
The card does not display if it cannot find a mobiled device (i.e. the LTE modem), even if you have marked it as visible. 

Run the following command via PuTTY or whatever SSH client you use:
```
transformer-cli get rpc.mobiled.DeviceNumberOfEntries
```
It should return 1. If it returns 0, the LTE modem is not functioning, and the card won't display.

Do you have a USB disk/whatever plugged in to the DJA0231? There are known issues where a USB device can draw too much power and prevent the LTE modem getting enough current to start. Otherwise, it could just be a faulty LTE module. Either will cause the card to not display.

**Comment by Bushy2022** [comment]
Thanks for the prompt response, but where do I find transformer-cli, i get error that command is not available.

**Comment by Bushy2022** [comment]
Thanks, my bad got 0 response

**Comment by seud0nym** [comment]
If you don't have any USB devices plugged in, then it could be that your LTE module has died.
