### ISSUE TITLE
Possible to add support for OpenClash?

### ISSUE THREAD

**Issue by shermanx** [seud0nym/tch-gui-unhide#101]
Hi seud0nym
Love your great work!
Is there any chance you would like to add support to incorporate this app please?
https://github.com/vernesong/OpenClash/releases

Also, I tried to install luci gui by 'opkg install luci'. Installation process went ok without error, but it seems I can't figure out how to access it, can't find any server/port info in nginx config, any idea maybe?

Thanks.

**Comment by seud0nym** [comment]
LuCI does not use nginx. It uses uhttpd, I think. I would have thought it would have been installed as a dependency. You probably need to tweak the config to ensure there is no conflict with nginx (or with nhttpd if you have a Gen 1/2/3 because that is what DumaOS uses).

Looking at the dependencies for OpenClash, it needs some kernel mods, which are probably not installed and you won't be able to find, and it needs ip6tables-mod-nat, which you also won't be able to find for these devices.

Sorry, but there is nothing I can add to tch-gui-unhide to support this.
