### ISSUE TITLE
After running reset-to-factory-defaults-with-root I lose ability to sftp

### ISSUE THREAD

**Issue by ilium007** [seud0nym/tch-gui-unhide#102]
I ran reset-to-factory-defaults-with-root and then attempted to scp the tch-gui-unhide tar.gz but that now fails. I have rooted these boxes plenty of times and have always been able to scp the tar.gz file.:

```
❯ scp 20.3.c.tar.gz 192.168.102.1:/root/
Warning: Permanently added '192.168.120.1' (ECDSA) to the list of known hosts.
ash: /usr/libexec/sftp-server: not found
scp: Connection closed
```

**Comment by seud0nym** [comment]
I doubt that it is anything to do with reset-to-factory-defaults-with-root.

According to [this](https://undeadly.org/cgi?action=article;sid=20210910074941#:~:text=By%20default%2C%20scp%20%281%29%20now%20uses%20SFTP%20protocol,-current%29%20now%20defaults%20to%20using%20the%20SFTP%20protocol%3A) the default for scp now is to use sftp, which is what appears to be happening to you. Maybe your scp version has been updated since you last tried it?

Try running scp with the -O flag.

**Comment by seud0nym** [comment]
Please re-open if confirm issue with reset-to-factory-defaults-with-root.
