### ISSUE TITLE
Samba 36 server share config

### ISSUE THREAD

**Issue by shermanx** [seud0nym/tch-gui-unhide#103]
Hi seud0nym, 

tch-gui-unhide-xtra.samba36-server installed successfully.

I tried to configure the samba share a bit so I can access the $home folder for root or any other new user created, however, I can't figure out how to do so with /etc/config/samba. There is a line there: option configsdir '/var/etc/smb.auto', but nothing there. 

USB stick is always automatically shared, so smbd is working fine at least.

Btw, I also can't see a smbd running in ps which is a bit weird?

Any advice please? Thanks.

**Comment by seud0nym** [comment]
> I can't figure out how to do so with /etc/config/samba

Have a look a the OpenWrt page for SAMBA for how to configure users and /etc/config/samba:

https://openwrt.org/docs/guide-user/services/nas/samba_configuration

> I also can't see a smbd running in ps which is a bit weird?

What firmware version are you using? You should only install SAMBA 3.6 on the 17.2 and 18.1.c firmware. The 20.3.c firmware contains NQE rather than SAMBA, and does not require the SAMBA 3.6 update to upgrade to SMBv2 and inter-operate with Windows 10.

**Comment by shermanx** [comment]
Yep, it's NQE running on 20.3.c. I'll try to figure this out. Thanks.

**Comment by seud0nym** [comment]
You may need to RTFD to undo the effects of the forced install of SAMBA 3.6. It may have broken NQE. After that, you should be able to configure using the standard OpenWrt instructions. Adding users is done with the `nqcsctrl` tool.
