### ISSUE TITLE
Can't reinstall tch-gui-unhide after safe firmware upgrade "Permission denied" Technicolor DJA0231

### ISSUE THREAD

**Issue by SakifX9** [seud0nym/tch-gui-unhide#116]
I am trying to install this after upgrading to 20.3.c.0432-MR21-RA but I keep getting permission denied 

![image](https://user-images.githubusercontent.com/16516667/200511076-d498728b-09f7-407d-8644-b3f266e4e57b.png)

**Comment by seud0nym** [comment]
When you run `safe-firmware-upgrade` with the version 18 or 20 firmwares, you need to specific the `-e` option to disable any 'noexec' flags on USB mounted filesystems. Otherwise, you get this issue with permission denied. (The other way it can happen is if you unpack the tar file on a Windows machine and then SCP the individual files up, but I assume you haven't done that.)

You have two choices: 

1. Copy the scripts to the internal flash memory (/root for permanent retention or /tmp for temporary) and then run them from there; or
2. Prefix the  scripts with `sh`. e.g. `sh de-telstra -A`
