### ISSUE TITLE
Disable logging + other processes?

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#120]
Hey, I'm trying to run Adguard on my router but I am experiencing frequent reboots. Looking at RAM and CPU usage, I see that it's always near 100% right before it "crashes" (reboots).

Top reports the following processes as using the most resources
```
10972     1 root     S    44484  10%  38% /usr/bin/mmpbxd -q -t 2
 1731     1 root     R     6928   2%  27% /sbin/logd -S 4096 -W 1000
 5124     1 root     R    45120  10%  11% lua /usr/bin/transformer
 5361     1 root     R    10148   2%   3% {mobiled} /usr/bin/lua /usr/bin/mobiled
```

Do you know what each does? Logd especially seems redundant, how can I disable that? 
dnsmasq is also up there, disabling it doesn't break anything (I'm using Adguard's DHCP server) so is it fine to do so?

**Comment by seud0nym** [comment]
I recently discovered what you have found - there is an incompatibility with mmpbxd when running AdGuard Home on these devices. What I have observed is that mmpbxd will _NOT under any circumstances_ use AdGuard for DNS resolution. It _insists_ on dnsmasq being used to resolve the IP of the VoIP server. I have no idea why.

What it causes though is exactly what you have seen. mmpbxd continually tries to resolve the primary registrar using dnsmasq, which isn't available. Each time it fails, it immediately tries again, causing higher than normal CPU usage. Then logging (logd) also starts using more CPU, because it is getting lots of log messages quite quickly. 

The transformer process allows the web GUI to modify the system settings, so you probably had the GUI open as well. mobiled looks normal.

Because mmpbxd can't resolve the primary registrar address, you end up with you number showing as unregistered. 

Toggling WAN Supervision isn't what caused your number to become unregistered. It is the DNS resolution problem. 4G backup is controlled by WAN Sensing, but WAN supervision is used to let WAN Sensing know there is an issue. It will probably be fine without it, but I haven't tried.

To try and reduce RAM usage, run `de-telstra` but add the `-M` flag. It will stop unnecessary or unused services.

If you disable lte-doctor-logging, the Mobile Diagnostics chart won't work.

I hadn't noticed the telemetry daemon. It looks like it might be part of DumaOS. I will look at adding it to de-telstra.

The simplest solution to the mmpbxd/dnsmasq issue is to use the IP address instead of the domain name as the Primary Registrar.

**Comment by seud0nym** [comment]
The suggestion to run `de-telstra -M` is already there. I will add the info about mmpbx.

**Comment by seud0nym** [comment]
You have to specify the overrides after `-M` e.g. `./de-telstra -M -ty`

**Comment by seud0nym** [comment]
Yes. The "normal" flags just disable service in configuration, but many of them still run and take up some memory, even though they aren't doing anything. `-M` stops them running and then disables the init scripts as well so that they can't take up any memory at all.

I only added the auto update because there was a time when the manual update (when prompted by AGH in the GUI) was broken. But I will think about making it weekly.

**Comment by seud0nym** [comment]
When you open up Telephony, does it show as enabled or disabled in the Global tab?

You can have a look at log messages with:
```
logread -e mmpbxd
```

**Comment by seud0nym** [comment]
But what is it resolving it to? `wa.hybrid.connect.telstra.com` must be only available from internal Telstra DNS servers, because no IP address is returned when I try to resolve it.

You either need to find its IP address and replace the registrar with the IP as I suggested (which was the only way I could get it to work) or add the Telstra DNS Servers as upstream resolvers.

**Comment by seud0nym** [comment]
You could try copying and pasting this as soon as you get a session:
```
echo "uci set mmpbx.global.enabled='0'">/etc/uci-defaults/zzz-9999-stopvoip;chmod +x /etc/uci-defaults/zzz-9999-stopvoip
```
That will create a run-once script that will disable telephony on the next crash/reboot.

This should show you the default Telstra DNS Servers:
```
transformer-cli get rpc.network.interface.@wan.dnsservers
```

**Comment by seud0nym** [comment]
You will have to specify the Telstra DNS Server on the nslookup:
```
nslookup wa.hybrid.connect.telstra.com n.n.n.n
```
where n.n.n.n is one of the Telstra DNS servers you got off the `transformer-cli` command I gave you.

No. agh-setup disables dnsmasq. It has to so that there is no conflict on port 53. It is the only way AGH can be installed on the device. There are people using it successfully, but they probably aren't using it with VoIP.

**Comment by seud0nym** [comment]
This makes no sense. 1.0.0.1 is the Cloudflare alternate DNS Server.

But if it works, then great.


------ Original Message ------
From "_Qubarf" ***@***.***>
To "seud0nym/tch-gui-unhide" ***@***.***>
Cc "Stephen Stevens" ***@***.***>; "Comment" 
***@***.***>
Date 12/12/2022 7:25:39 PM
Subject Re: [seud0nym/tch-gui-unhide] Disable logging + other processes? 
(Issue #120)

**Comment by seud0nym** [comment]
I am glad you have found a solution that works for you. I did send a reply email last night but it seems to have gotten lost.

I am surprised that it doesn't resolve the address again when the session expires and is re-established.

I still think the simplest and cleanest solution is to use the IP address of the registrar. 

Since you have a working connection, you can get the IP address from the log:
```
logread -e mmpbxfwctl
```
The IP address you need will be after the --src option.

**Comment by seud0nym** [comment]
I have just pushed up a new version of `agh-setup`. It has a new `-k` option that allows you to keep dnsmasq as the primary resolver, but it will pass all DNS queries to AdGuard Home to be resolved. It will also turn off dnsmasq caching so hopefully the memory impact won't be too bad.

> You should really put this sort of stuff in the README, it would have helped me out so much

That's a bit rude. I only recently found the mmpbxd issue, and I do actually have other things to do. It was on my list to do, but since nobody had reported it as an issue (until you) it didn't have any priority.

> is there a way to get hostnames to show in the main interface when using AdGuard as the DHCP server?

Not as far as I know. Be aware that if you try the new `-k` option, it forces the `-d` option and dnsmasq will be the DHCP server.

**Comment by seud0nym** [comment]
Hang on. Don't try the new version yet. There might be a bug.

**Comment by seud0nym** [comment]
Ignore the previous message. It is okay - just an incorrect message that I will fix.

**Comment by seud0nym** [comment]
> `logread -e mmpbxfwctl` doesn't return anything, mmpbxd is running, calls are being received.

That is strange. What is supposed to happen is that once the SIP session is established, it creates a firewall rule to ensure the inbound calls can be received. It may be just a logging system issue if you are on the 20.3.c firmware - it can be a bit flaky.

Try this command to see if the firewall rule is there:
```
iptables -t filter -L MMPBX -n
```

**Comment by seud0nym** [comment]
Oh, okay, so it is using IPv6 for transport instead of IPv4. I have not tried an IPv6 address and neither of my VoIP providers use IPv6 so I can't test it. Anyway, you can try putting in that IPv6 address as the registrar and see if it registers.

**Comment by seud0nym** [comment]
```
uci set mmpbxrvsipnet.sip_net.primary_registrar='2001:8006:3520:1:7:e1c0:0:11'
uci commit mmpbxrvsipnet
/etc/init.d/mmpbxd restart
```

**Comment by seud0nym** [comment]
No, that will happen automatically.

**Comment by seud0nym** [comment]
How is your memory usage?

**Comment by seud0nym** [comment]
No, you can remove that.

**Comment by seud0nym** [comment]
I don't know about the RAM usage relationship to free memory. The problem with DJA0231 is there really isn't enough RAM to run AdGuard Home. I run my AdGuard Home on a separate Linux box, so that I can have more lists enabled.

Hostnames won't work because all the queries are coming from through the router. There is no work-around. You could turn on DNS Query logging and then you would be able to search the log for the source host.
