### ISSUE TITLE
IPV6 rDNS not working

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#124]
As the title says, IPV6 addresses are shown for local devices rather than their hostnames unlike for IPV4 address

**Comment by seud0nym** [comment]
I don't think rDNS is possible for IPv6. IPv6 address management is very flaky. 

For example, I update my AdGuard Home Persistent Clients with all known IP addresses every 6 minutes, but there are always IPv6 addresses that are making DNS requests that are not associated with a Client. When I investigate them, it turns out to be an IPv6 address that is valid, it is just that DJA0231 doesn't know about them.  Right now, the Devices list on my primary DJA0231 shows that my PC has an IPv4 address and NO IPv6 addresses. Running ipconfig on my PC shows that I have 4 IPv6 addresses. The DJA0231 has assigned them but just doesn't know who is using them.

Even if I do a rDNS request for an IPv6 address that is showing in the Devices list, that it obviously knows about, it still fails to return the hostname.

I have done some Googling and I can't find an answer. If you have found/can find something that will fix it, I would be happy to have a look at the link.

**Comment by seud0nym** [comment]
The problem is that the solutions suggested in that issue won't work if the router doesn't know how to get the hostname from the IPv6 address. This is what I meant in my reply above: my Windows PC has an IPv6 ULA that was assigned by my DJA0231. But when I query the DJA0231 to give me the host name for that IPv6 address, it comes back with NXDOMAIN (it doesn't know):

```
root@DJA0231-Study:~# dig -x fd10:20:30:40:1234:5678:90ab:cdef

; <<>> DiG 9.14.8 <<>> -x fd10:20:30:40:1234:5678:90ab:cdef
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45044
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;f.e.d.c.b.a.0.9.8.7.6.5.4.3.2.1.0.4.0.0.0.3.0.0.0.2.0.0.0.1.d.f.ip6.arpa. IN PTR

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 05 17:19:55 AEDT 2023
;; MSG SIZE  rcvd: 101
```
_(Real ip has been substituted with fake, but you get the idea - you can try it yourself)_

However, when I was searching based on some other ideas in that issue, I came across this:

https://github.com/AndreBL/ip6neigh

I haven't tried it, but I did a quick check on my DJA0231 running 20.3.c.0432-MR21.1-RA, and the dependencies are already installed, so it _should_ work. I will give it a try at some point (because this really annoys me too :-), but if you want to give it a go, that would be great.

**Comment by seud0nym** [comment]
> What is `LocalAdmin`?

I don't have any of those. I have a couple of `Unknown`, but I haven't downloaded the OUI database yet. 

Could they be Locally Administered Addresses? 
https://macaddress.io/faq/what-are-a-universal-address-and-a-local-administered-address

> In any case, it seems AdGuard doesn't support client settings based on hostname so this won't work :(

> Edit: man, this sucks - I can't get ip6neigh to add lan name to addresses nor can I get dnsmasq to not add that so ultimately I face the same problem as before

[agh-clients.lua](https://github.com/seud0nym/tch-gui-unhide/tree/master/adguard#agh-clientslua) will fix this. It runs every 6 minutes and creates/updates AdGuard Home clients (using their host name), and assigns all their IP addresses to each client. You will only see the host name in AdGuard Home (which in fact will be the client name).

You can also then update the clients and change their settings, which you can't do with rDNS resolved names.

**Comment by seud0nym** [comment]
> In your query logs, are you seeing two variations of client names depending on whether it's IPv4 or IPv6?

No.

> Is it possible to fix this duplication so that requests coming from IPv4 as well as IPv6 resolve to the same hostname (doesn't matter to me if they're prefixed with `.strax`)

That is what the script will do. And it will remove the domain suffix (like `.strax`).

> I'm guessing this means it worked?

That is similar what I see.

> How can I apply a common set of rules for several devices?

Do you mean within AdGuard Home? I don't know.

> the script resets all the rules

I don't use the client based rules, but it shouldn't. All it should do is update the associated IP addresses. I will have a look.

> there are still duplicates (albiet with the same name) of same clients for both IPv4 and IPv6 addresses :(
>
> I'm struggling to understand what the script actually fixes

For devices that use MAC randomisation, it will combine them back to a single name.

There should be a single Client Name, with multiple IP addresses (both IPv4 and IPv6) associated with it. You can see the counts per client (aggregated across all IP addresses for the client) in the Client Settings screen. In the Query Log, you can query by Client Name and it will show you all requests from that client across all IP addresses (both IPv4 and IPv6).

However, in the Dashboard, you will still see individual IP addresses with the correct Client Name. I haven't seen a setting to change that.

Before I started using `ipv6neigh`, I still had IPv6 addresses not associated with a Client Name. That is fixed using the combination of `ipv6neigh` and `agh-clients.lua`.

**Comment by seud0nym** [comment]
At the moment everything is identified by host name. However, it is possible to load the MAC address into the Client field (along with the associated IPv4/6 addresses) and then update based on MAC address rather than host name. If there is a new client it would get the host name by default, but you would be able to edit the Client in AdGuard Home and change the name to whatever you want. You would also be able to move the MAC addresses to a user-based Client (i.e. it could have multiple MAC addresses associated with it).

It would mean a large restructure of the current `agh-clients.lua` script, but it might be better and more flexible. I will have to have a think on whether it is possible.

**Comment by seud0nym** [comment]
I have uploaded a new version of `agh-clients.lua` that will not overwrite existing configuration changes that you make in AdGuard Home. It is also optimised so that it no longer does an update if nothing has changed.

However, my idea of using the MAC address and combining multiple devices under one user Client won't work. The AdGuard Home Client GUI won't save if there are MAC addresses in the IDs if AGH is not handling DHCP.

**Comment by seud0nym** [comment]
I think it is better to leave credit where it is due, especially since you have gone to the trouble of creating a public repo.

I have added the repo info into the AdGuard README.md.

**Comment by seud0nym** [comment]
I think I have finally found out what caused this name resolution problem with mmpbx and AdGuard Home.

You should be able to fix an existing system with the following commands:
```
uci set dhcp.main.localuse='1'
uci set dhcp.main.port='0'
[ "$(uci -q get dhcp.main.server)" = "127.0.0.1:53535" ] && uci delete dhcp.main.server && uci add_list dhcp.main.server='127.0.0.1'
uci commit dhcp
/etc/init.d/dnsmasq restart
```

The `agh-setup` has been corrected.
