### ISSUE TITLE
DHCP routed mode not working via IPoE 20.3.c.0389-MR20-RA

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#125]
I currently have two DJA0231; I'm having an issue with DHCP routed mode not working via IPoE on 20.3.c.0389-MR20-RA. To get this online I need to set the connection mode to "Static IP mode" and input IP address details but on version 18.1.c.0241 via DHCP routed mode.

18.1.c.0241
https://i.imgur.com/yR2uXr3.png

20.3.c.0389
https://i.imgur.com/SiQNbc3.png
https://i.imgur.com/F1OaZlh.png

**Comment by seud0nym** [comment]
Hi.

Who is your ISP/RSP?
What is your connections type (FttN/HFC/FttP etc.)?

Have you tried connecting without tch-gui-unhide installed?

**Comment by unclelez** [comment]
Hi,

My ISP is AAPT and I’m using NBN FttP 100/40.

I’m unable to use it without tch-gui-unhide because my ISP only uses IPoE.

Happy to try any recommendation you may have

Thank you

Nick

**Comment by seud0nym** [comment]
IPoE is the same as DHCP Routed. It is the default on these devices, because Telstra also uses IPoE.

If you can, I would run the [reset-to-factory-defaults-with-root](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#reset-to-factory-defaults-with-root) script followed by [de-telstra](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#de-telstra) to make sure you don't lose root access when you plug it into the NTD.

Then get connected using the DJA0231 without tch-gui-unhide. That way we can ensure that it is tch-gui-unhide that is causing the problem if you can get connected without it being installed.

**Comment by unclelez** [comment]
Thank you for your help. The issue was on the ISP side

**Comment by seud0nym** [comment]
Glad you got it sorted.
