### ISSUE TITLE
WAN doesnt connect on first boot

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#138]
Hi and thank you for your efforts.

I'm experiencing an issue on the first boot of my device after running de-Telstra and tch-gui-unhide, I enter my Static WAN settings but only the WWAN will connect, Broadband is detecting VDSL is up but the WAN will only connect once I disable WWAN and reenable it.

I'm using a static IP address and have WAN sensing disabled.

Any help would be great

**Comment by seud0nym** [comment]
There isn't anything in either de-telstra or tch-gui-unhide that changes the way that your device detects the WAN or connects to it. 

de-telstra does make some minor changes to WAN Sensing to turn off data collection workers and fix an APN check in WAN Sensing failover, but since you aren't using WAN Sensing they obviously aren't an issue. tch-gui-unhide just gives your the ability to configure things that you can't normally do through the Telstra GUI.

When you say first boot, do you mean that subsequent reboots all connect successfully?

Are you using the Permanent WWAN configuration in place of WAN Sensing?

Also, just FYI: I don't have a static IP or VDSL connection (IPoE HFC here), so my experience is very limited with both of those.

**Comment by unclelez** [comment]
Thanks for the explanation.

I was able to fix the issue on my config
