### ISSUE TITLE
Internet Access stuck on "connecting". Wireless control confusion

### ISSUE THREAD

**Issue by gsstudios** [seud0nym/tch-gui-unhide#14]
I've been running tch-gui-unhide and it is been pretty stable for the most part. Awesome work btw.
However there are some minor annoyances that I've found. 

Device: DJA0230 (Telstra Smart Modem)
Firmware: 18.1.c.0549-MR17-RB

- In the Internet Access card, the status is stuck on "connecting". My uptime has been more than 10days. I haven't found anything interesting in logs
- When I first installed your mod (de-telstra+tch-gui-unhide script), my router was having trouble maintaining a stable connection to my ISP. Logs indicated something to do with the wansensing, hence I switched it off and restarted my device (which fixed this). 
- I'm unable to confirm that wireless control is working on my device. If the current time is in-between the start/stop time schedule, does the rule still apply (e.g. does the current time have to be before the schedule)? Is there a delay for the changes to apply?

**Comment by seud0nym** [comment]
What is your connection mode (DHCP/PPPoE/Static)? I assume it is PPoE (because DHCP only shows connecting if it doesn't have an IP address), so what is the output from this command:
```
transformer-cli get rpc.network.interface.@wan.ppp.
```

I suspect the wansensing problem and the "connecting" problem are symptoms of the same issue. However, I don't change any fundamentals of the router - only things that affect the GUI. (At least, that is the aim...)

I "borrowed" the wireless control GUI from tch-nginx-gui. I may have missed something. I will need to investigate further.

**Comment by gsstudios** [comment]
I'm using PPPoE connection mode. 
> root@DJA0230:~# transformer-cli get rpc.network.interface.@wan.ppp.
rpc.network.interface.@wan.ppp.state [string] = connected
rpc.network.interface.@wan.ppp.uptime [string] = 1165757
rpc.network.interface.@wan.ppp.ll_intf [string] = eth4
rpc.network.interface.@wan.ppp.error [string] =
rpc.network.interface.@wan.ppp.ll_dev [string] = eth4

**Comment by seud0nym** [comment]
That is just weird. The code is pretty simple. It basically just shows what is in `rpc.network.interface.@wan.ppp.state`, unless it is blank or "authenticating", in which cases it shows "connecting".

Is it showing correctly when you open the Internet card?

**Comment by gsstudios** [comment]
> 
> 
> That is just weird. The code is pretty simple. It basically just shows what is in `rpc.network.interface.@wan.ppp.state`, unless it is blank or "authenticating", in which cases it shows "connecting".
> 
> Is it showing correctly when you open the Internet card?

Here are some screenshots:
![image](https://user-images.githubusercontent.com/9124784/101270510-d5386b80-37cd-11eb-9db1-014cb4b9043d.png)
![image](https://user-images.githubusercontent.com/9124784/101270517-e7b2a500-37cd-11eb-8e0c-befd4edb27d0.png)
![image](https://user-images.githubusercontent.com/9124784/101270549-37916c00-37ce-11eb-8b4f-d1ce072f7b43.png)

**Comment by seud0nym** [comment]
Thanks for the screen shots - very helpful, because I got it in to my head that it was the other way around. So the card on the dashboard is correct, but the screen (in the UI jargon, the "modal") is incorrect.

That field is actually set 2 different ways - once when you initially open it, and then it auto-updates in the background every 5 seconds. It also looks like what is shown is subject to different conditions on the card, at first display, and during auto-update!

Is it correct (i.e. showing Connected) when you first open the modal, and then it changes to Connecting after 5 seconds, or is showing Connecting as soon as you open it?

Still looking into Wireless Time of Day. I agree it is not working. I don't believe that it works in the Ansuell custom GUI, either, which is where I got some of the updates from.

**Comment by jmytch** [comment]
> 18.1.c.0549-MR17-RB

Sorry to hijack this but how are you getting that firmware? I looked at the https://hack-technicolor.readthedocs.io/en/stable/Repository/#telstra-smart-modem-gen1 and couldn't find the 549 firmware that you mentioned? 

I'm on the 18.1.c.0462-950-RA for mine :-/

**Comment by seud0nym** [comment]
I always use the "latest" version of the repository: 
https://hack-technicolor.readthedocs.io/en/latest/Repository/#telstra-smart-modem-gen1

That firmware is here:
http://fwstore.bdms.telstra.net/Technicolor_vbnt-v_18.1.c.0549-MR17-RB/vbnt-v_18.1.c.0549-MR17-RB.rbi

**Comment by jmytch** [comment]
Oh that's interesting, I never knew they have "latest" repository besides their "stable" version. Thanks for the link, I might update the firmware later tonight with your tool :) 

Bookmarked the link as well for future reference 👍

**Comment by gsstudios** [comment]
> Is it correct (i.e. showing Connected) when you first open the modal, and then it changes to Connecting after 5 seconds, or is showing Connecting as soon as you open it?
It is showing connecting as soon as I open it and doesn't change even after I click on refresh

**Comment by seud0nym** [comment]
I have made a couple of minor changes and added some logging, but I can't test it (not PPPoE here).

Can you copy the attached file up to your device, and then execute the following commands from the directory you copied it up to:
```
mv /www/snippets/internet-pppoe-routed.lp /www/snippets/internet-pppoe-routed.lp.old
tar -xzvf internet-pppoe-routed.lp.tar.gz -C /www/snippets/
```

This will log some information about what is actually being called when you open the Internet Access screen. One of 2 things will happen when you open the screen - it won't open or it will :-)

- If it doesn't open, execute this command: `logread | tail -n 20`
- If it does open, execute this command: `logread | grep "get_ppp_state called with parameters"`

In either case, copy the output, remove any personal stuff, and post it back here.

If it doesn't open, it means I have made a typo. Hopefully I haven't, and we will get some info to track down the problem.

To undo the change, execute the following command:
```
mv /www/snippets/internet-pppoe-routed.lp.old /www/snippets/internet-pppoe-routed.lp
```


Thanks.

[internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5648390/internet-pppoe-routed.lp.tar.gz)

**Comment by gsstudios** [comment]
> I have made a couple of minor changes and added some logging, but I can't test it (not PPPoE here).
> 
> Can you copy the attached file up to your device, and then execute the following commands from the directory you copied it up to:
> 
> ```
> mv /www/snippets/internet-pppoe-routed.lp /www/snippets/internet-pppoe-routed.lp.old
> tar -xzvf internet-pppoe-routed.lp.tar.gz -C /www/snippets/
> ```
> 
> This will log some information about what is actually being called when you open the Internet Access screen. One of 2 things will happen when you open the screen - it won't open or it will :-)
> 
>     * If it doesn't open, execute this command: `logread | tail -n 20`
> 
>     * If it does open, execute this command: `logread | grep "get_ppp_state called with parameters"`
> 
> 
> In either case, copy the output, remove any personal stuff, and post it back here.
> 
> If it doesn't open, it means I have made a typo. Hopefully I haven't, and we will get some info to track down the problem.
> 
> To undo the change, execute the following command:
> 
> ```
> mv /www/snippets/internet-pppoe-routed.lp.old /www/snippets/internet-pppoe-routed.lp
> ```
> 
> Thanks.
> 
> [internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5648390/internet-pppoe-routed.lp.tar.gz)

Here's the screenshot of the log output. This is after I click on the internet card to bring up the modal. I then re-open again later.

![image](https://user-images.githubusercontent.com/9124784/101294841-239d4700-386e-11eb-952d-ffdce8677ac3.png)

**Comment by seud0nym** [comment]
Thanks for doing that. 

The log shows that it should have initially shown as Connecting (@ 09:18:26 and 09:20:42), but then should have updated to Connected @ 09:18:32/09:20:48. I assume that it did not do that, since you didn't mention it, and that is REALLY annoying, because I just can't see why it isn't showing the correct status.

It is somewhat interesting that `wan_ppp` is empty after the first call each time, then updates to "connected", but I don't really understand why or what it means, especially since it doesn't update anyway.

Here is another version for you to try (thanks for your patience). This version will re-retrieve the state if it is initially empty. I have also added some more log messages.

If you haven't undone the version I sent you last time, then just do the `tar` command again on the attached version, and then the `logread` command again when you open the modal. If you have undone it, do the `mv` first.

[internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5649845/internet-pppoe-routed.lp.tar.gz)

**Comment by gsstudios** [comment]
> Thanks for doing that.
> 
> The log shows that it should have initially shown as Connecting (@ 09:18:26 and 09:20:42), but then should have updated to Connected @ 09:18:32/09:20:48. I assume that it did not do that, since you didn't mention it, and that is REALLY annoying, because I just can't see why it isn't showing the correct status.
> 
> It is somewhat interesting that `wan_ppp` is empty after the first call each time, then updates to "connected", but I don't really understand why or what it means, especially since it doesn't update anyway.
> 
> Here is another version for you to try (thanks for your patience). This version will re-retrieve the state if it is initially empty. I have also added some more log messages.
> 
> If you haven't undone the version I sent you last time, then just do the `tar` command again on the attached version, and then the `logread` command again when you open the modal. If you have undone it, do the `mv` first.
> 
> [internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5649845/internet-pppoe-routed.lp.tar.gz)

![image](https://user-images.githubusercontent.com/9124784/101415808-a260b580-393c-11eb-8a42-9889e6a0c804.png)
Works great! Thanks

**Comment by seud0nym** [comment]
I think I have found the issue with Wireless Time of Day processing. Fixed in next release.
