### ISSUE TITLE
Internet Access: WAN Failover

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#148]
Hi, and thank you for your help.

I'm currently expensing an issue that might be a bug. I'm using a static IP with NBN FTTP Fixed Ethernet and WWAN
(WAN Sensing Off). When the Fixed Ethernet goes offline, it fails to route the traffic via the WWAN but failover works fine when the Broadband is set to VDSL2

The Broadband tab show `Fixed Ethernet disconnected` and the WWAN online but the light on the front of the router is Green.

Any help would be great.

**Comment by unclelez** [comment]
![image](https://user-images.githubusercontent.com/112058383/235336978-03296f9a-cc33-447a-94a4-740824b4237f.png)

root@mymodem:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
--- 8.8.8.8 ping statistics ---
75 packets transmitted, 0 packets received, 100% packet loss
root@mymodem:~#

**Comment by seud0nym** [comment]
I guess you have turned on the Permanent WAN switch?

I will have to set up to do some testing. I can't test vDSL, but I can simulate FttP.

**Comment by unclelez** [comment]
Yes, permanent WAN is turned on. Failover via VDSL works fine. The issue is
only with Ethernet interface

**Comment by seud0nym** [comment]
Sorry, just double checking: you don't have IPv6 enabled at all, and the SIM profile is also IPv4 with no IPv6 enabled. Is that correct?

**Comment by unclelez** [comment]
Yes, IPv4 is only in use. All IPv6 is disabled

**Comment by seud0nym** [comment]
I have done a couple of tests and I can't reproduce your issue.

What does this command return when routing fails:
```
ip route show
```

**Comment by unclelez** [comment]
Output on Ethernet interface

`root@mymodem:~# ip route show
default via XXX.XXX.255.101 dev eth4 proto static metric 1 
default via XXX.XXX.164.201 dev wwan0 proto static src 125.168.164.200 metric 20 
XXX.XXX.164.192/28 dev wwan0 proto static scope link metric 20 
XXX.XXX.255.100/30 dev eth4 proto static scope link metric 1 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.2.0/25 dev wl0_1 proto kernel scope link src 192.168.2.126 
192.168.2.128/25 dev wl1_1 proto kernel scope link src 192.168.2.254 
239.0.0.0/8 dev br-lan scope link `

Output on VDSL2 interface

`default via XXX.XXX.164.201 dev wwan0 proto static src XXX.XXX.164.200 metric 20 
XXX.XXX.164.192/28 dev wwan0 proto static scope link metric 20 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.2.0/25 dev wl0_1 proto kernel scope link src 192.168.2.126 
192.168.2.128/25 dev wl1_1 proto kernel scope link src 192.168.2.254 
239.0.0.0/8 dev br-lan scope link `

**Comment by unclelez** [comment]
The LED will always stay green regardless if WAN cable is connected or not

![2023-05-09 21_40_28-Window](https://github.com/seud0nym/tch-gui-unhide/assets/112058383/ccd161e9-642b-43d5-bf4e-75eb1adb24b5)

**Comment by seud0nym** [comment]
The LED handling is really complicated, and doesn't understand when both wan and wwan are simultaneously enabled. Because it is really complicated, I haven't touched it, and I won't until I get a really good handle on what causes the LED state to change and how it is changed.

The status of "Ethernet disabled" is confusing - it just means that it is down. I will fix that in the next release.

Your routing tables look fine. Packets should follow the default route on the active interface with the lowest metric. So when your ethernet cable is pulled, it should ignore the XXX.XXX.255.101 route, and go to the default route with the next highest metric (XXX.XXX.164.201 metric=20).

I assume your VDSL2 routing table has no route with a metric of 1 because you don't actually have a VDSL connection.

I cannot explain why it is not working for you.

What does the following command show:
```
traceroute 8.8.8.8
```
(It probably won't work at all, but if it does it might tell us something...)
