### ISSUE TITLE
DumaOS Adblock issues on Release 2023.05.29

### ISSUE THREAD

**Issue by TheBlueJester** [seud0nym/tch-gui-unhide#154]
Howdy!

I unfortunately don't have particularly useful data on this particular issue. 
Telstra Gen 1 Modem. Firmware: 20.3.c.0432

After updating to the pre-release 2023.05.26 the adblocker within DumaOS stopped functioning. 
DNS requests were working, but the filtering wasn't being applied. 
Updated to the latest 20.05.29 and the issue continued. 
I re-ran de-telstra and tch-gui-unhide once more today but no improvement. Checked the output to make sure it was showing 20.05.29 version and it was.
(Also rebooted the Modem several times in the last few days hoping that would resolve it)

Manually uploaded 2023.05.16 to the device and re-ran tch-gui-unhide and the adblocking is back to working correctly. 

I know that's not a lot to go on, but I can't think of anything else to include that could be helpful.
Happy to try updating to latest again and do tests if that's at all helpful.

Thanks!

**Comment by seud0nym** [comment]
I can't find any information on how the DumaOS adblocker is implemented, so I can't tell what could be wrong. 

I can't think what change I made that would break it.

Can you tell if it is de-telstra or tch-gui-unhide that breaks it?

**Comment by seud0nym** [comment]
The only thing I can think of trying is this:

1. Revert back to 2023.05.16 and confirm DumaOS ad blocking is working.
2. Run this command: `uci show | sort > /tmp/2023.05.16.txt`
3. Apply 2023.05.29 and confirm DumaOS ad blocking not working.
4. Run this command: `uci show | sort > /tmp/2023.05.29.txt`

You can then zip up those files and attach them to this issue so that I can search for differences. 

If you are not comfortable doing that, then can you use a utility to show the differences between the files and just post the results.

**Comment by TheBlueJester** [comment]
I've generated the first text file.
I'll update to the latest with -U later today. Run tch-gui-unhide and test the ad-blocker and then run de-telstra if unhide didn't break it.
Thanks!

**Comment by TheBlueJester** [comment]
So I've run just tch-gui-unhide and then de-telstra for a couple of days now. Ad-blocking seems to be functioning fine. 
I can only guess it might have been the pre-release I used in-between, or possible something related to Wireguard DNS that originally cause my problems. 
In any case, everything is working on the current release now.
Sorry for the bother!

**Comment by seud0nym** [comment]
No bother. Thank you for the coffee!
