### ISSUE TITLE
Clicking Devices card goes to incorrect options menu...

### ISSUE THREAD

**Issue by rkaycom** [seud0nym/tch-gui-unhide#171]
Me again, on the TG800vac, when click on the Devices title card it takes you to the Local Network->Connected Devices instead of the Devices menu where you can configure the Bandwidth Monitor and see network map, etc, etc.

**Comment by seud0nym** [comment]
Damn. This was added in the last release so you can quickly get to the connected devices list from the Local Network tabs, and I made sure that clicking on the lines on the Devices card took you to the right tab structure, but I forgot about just clicking on the card header. I generally click on the inactive count so that it always shows both active and inactive clients by default.

As a short term workaround, clicking on any of the card items will take you to the correct structure.

**Comment by seud0nym** [comment]
You can test the fixes for #171, #172 and #173 by running:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by rkaycom** [comment]
All fixed!
