### ISSUE TITLE
Adblock extra 'unable to complete setup'

### ISSUE THREAD

**Issue by sumeetkpatel** [seud0nym/tch-gui-unhide#181]
On the Gen3 modem I am getting this:
`Firmware Version: 20.4.0428-MR1-RA`
```
root@CobraXh:/tmp/run/mountd/sda1/telstra/unhide# sh tch-gui-unhide-xtra.adblock setup
>> Determining installed and current versions of required packages...
>> Latest adblock version is 1.0.0-2
4.1.5-8 but only version 4.1 is supported - unable to complete setup
```
Any way to progress?

**Comment by seud0nym** [comment]
A new package called `adblock-fast` has been added to the repository, and it confused the version detection, which was just looking for package names starting with `adblock`.

I have committed a fix. Please download again and retry.

BTW: You really should consider upgrading your firmware to 21.4.0439. It is _significantly_ more stable.

**Comment by sumeetkpatel** [comment]
I started over.

Currently:
`Firmware Version: 21.4.0439-MR2.1-RA`
I tried adblock before unhide and it sent it into a boot loop.
I've reflashed from scratch and back to a working `21.4.0439-MR2.1-RA` unhide but without adblock.
Should I try to run adblock again post unhide or just wait until this is better supported?

**Comment by seud0nym** [comment]
A boot loop isn't usually a boot loop.  It is usually caused by an executable doing a core dump, and these devices are configured to automatically reboot on a core dump. There will be a core dump file in /root which will indicate which program caused the issue (unless you have since done a reset).

Anyway, I have installed adblock multiple times on 21.4 without issue, so I am not sure what caused it.

Yes, you should re-run the adblock setup. If you are concerned about it happening again, you can run the following command (in the same directory that extracted tch-gui-unhide):
```
sh reboot-on-coredump -off
```

After adblock is setup, you will need to re-run the `tch-gui-unhide` install to pick up the additional adblock card.

**Comment by seud0nym** [comment]
I have been able to reproduce the core dump/boot loop issue. I am working on a fix.

**Comment by seud0nym** [comment]
I have found the problem. The adblock package has a dependency on the full coreutils sort (instead of the cut-down sort provided by BusyBox on these devices). I have been trying to build a 64-bit version, and I thought it was working, but it wasn't. It was sort that was core dumping and causing the issue. I have reverted to a 32-bit version (which does run on the Gen 3) and it seems to be fixed now.
