### ISSUE TITLE
SMG3 as booster plugged in WAN port on main, shows 0 boosters?

### ISSUE THREAD

**Issue by bt** [seud0nym/tch-gui-unhide#188]
Hello,

I'm configuring an SMG3 that I recently purchased as a Booster in my home. I've followed the wiki to do so, and everything seems to be working fine however, when I plug a LAN port from main -> WAN port on booster, the interface on the main will show `0 Boosters connected`. In addition, the "booster" will fail to sync the SSIDs from the main.

If I however plug in the LAN port on main -> LAN port on booster, the interface will show `1 Boosters connected` and the SSID will sync correctly. That comes with a cosmetic side-effect in which the LED in the front will show red though.

This issue is referring to the step in the wiki that mentions the following:

```
After running the script, you can move the cable from the LAN port to the WAN port if you wish. This is not mandatory, as when the device is running in bridged mode, all 5 ports are effectively LAN ports.
```

Might I be doing something wrong?

**Comment by seud0nym** [comment]
No, I have my Gen 3 booster connected to the main Gen 3 via the WAN port.

What does the following command return on the booster?
```
uci show network.lan.ifname
```

**Comment by bt** [comment]
```
root@mymodem:~# uci show network.lan.ifname
network.lan.ifname='eth0 eth1 eth2 eth3 eth4'
```

**Comment by seud0nym** [comment]
Well, that looks fine. It says the WAN port (eth4) is part of the LAN bridge. We should double check with:
```
brctl show
```
It should show eth0-eth4 plus the WiFi interfaces (including backhaul), so wl0, wl0.1 and wl1.

What firmware version are you running?

What options did you use when you ran the `bridged-booster` script?

**Comment by bt** [comment]
```
root@mymodem:~# brctl show
bridge name	bridge id		STP enabled	interfaces
br-Guest		7fff.a0b53cc167d5	yes		dummy0
br-lan		7fff.a0b53cc167d5	yes		eth0
							eth1
							eth2
							eth3
							eth4
							wl0
							wl0.1
							wl1
```

Version: `Bootloader: 21.4.0439-5940000-20230531230645-6689aedff4a3c73b4211a14f1cd9a3ba4ffcd825`

`bridged-booster` was just run with `-y -i 192.168.0.50` (to set the IP address)

**Comment by seud0nym** [comment]
No, if it works on a LAN port then the main SMG3 sounds like it is fine.

The only difference in my install is that I used `-d` instead of `-i ip` and I also added -6 to add IPv6.

I also don't have a Guest bridge in `brctl`. Not sure why - I have not removed the Guest WiFi (although it is disabled) because I was trying some things to see if I could have Guest propagated in the same way the main SSIDs do (that doesn't work so far).

I will double check the instructions to see if something doesn't work on the SMG3. I will just have to pull out my test device, so it might take me a while.

**Comment by seud0nym** [comment]
Well, I can reproduce it on my test SMG3, but I can't work out why at this stage. I will keep looking.

**Comment by bt** [comment]
> Well, I can reproduce it on my test SMG3, but I can't work out why at this stage. I will keep looking.

Thanks mate, I appreciate it 😀

**Comment by seud0nym** [comment]
I have no idea.

On my "real" booster, I have the cable connecting to the controller plugged into the WAN port and it works fine. All other LAN ports are used for other devices and all also are fine.

My "test" SMG3 will _not_ connect the the controller on the WAN port. I have tried every configuration change I can think of. I have even restored the configuration backup from my working booster to the test device (so they are effectively the same) and it _still_ won't connect as a booster. Using any of the LAN ports works, and the WAN port works with any other device plugged in (they connect and get a DHCP IP address without any issues).

I am thinking it might be hardware specific? Something slightly different in the internal switch between my current booster and my test/you booster SMG3? I just don't know.

Does your WAN port work as a LAN port if you connect to the primary with one of the LAN ports?

**Comment by seud0nym** [comment]
As a follow up, I tried my spare SMG3 and I get the same result: it will not connect as a booster over the WAN port.

I think that the best thing to do is to update the booster README to say that it may not work on the SMG3.

**Comment by bt** [comment]
Sorry for the late reply, got a bit bogged in work.

> On my "real" booster

Your "real" booster is an SMG3 right? Not the Wi-Fi Booster Gen 3?

> Does your WAN port work as a LAN port if you connect to the primary with one of the LAN ports?

Yeah it does, maybe the Airties meshing binaries are not specifically looking at the WAN port to sync?

Now given this is the new suggestion -- it brings up a cosmetic issue which is the fact that without the WAN port plugged into something, the LED light in the front will always be red. Is there any script/code/hack that can just force it to be green?

**Comment by seud0nym** [comment]
> Your "real" booster is an SMG3 right?

Yes.

> Yeah it does, maybe the Airties meshing binaries are not specifically looking at the WAN port to sync?

There is something blocking the IEEE1905 packets over the WAN port, the same way that older/cheaper switches don't work between the controller and the booster. I just can't work out what it is.

There are config files in the airites directories, but they don't appear to be used.

The binaries themselves are the same on the device that works and the ones that don't.

> Is there any script/code/hack that can just force it to be green?

If you plug a LAN device into the WAN port, it will go green.

If you don't want to do that, this should _probably_ work (I can't test it right now):
```
echo none > /sys/class/leds/front:green/trigger
cat /sys/class/leds/front:green/max_brightness > /sys/class/leds/front:green/brightness
```

You can use `blue`, `cyan`, `magenta` or `orange` (or `red`, of course) instead of green. `max_brightness` is 255, so use a number less than that to dim the led.

You may need to set the trigger on the other colours to `none` as well, to stop your choice being overridden. Or maybe stop and disable the led and ledfw services. Not sure.

**Comment by seud0nym** [comment]
This will permanently set the front LED to green, whether or not anything is plugged into the WAN port:

```
sed -e '/bridge_o[nf]*line =/,/}/{
  s/true/false/
  /blue/a\           staticLed\("front:green", true\),
}' -i /etc/ledfw/stateMachines.lua
/etc/init.d/ledfw restart
```

If you want to restore it to default actions, then:
```
cp -p /rom/etc/ledfw/stateMachines.lua /etc/ledfw/stateMachines.lua
/etc/init.d/ledfw restart
```
