### ISSUE TITLE
Sims not connecting

### ISSUE THREAD

**Issue by mike777z** [seud0nym/tch-gui-unhide#189]
Hey Stephen,

I have noticed an issue with my sims not connecting. I'm using `DJA0230` running firmware `20.3.c.0389-MR20` and using the latest tch gui unhide (`2023.12.21`). Telstra sims work fine but any other carrier sim doesn't work. The sim seems to find signal and register but wwan doesn't come up. Based on the logs, it looks like netifd fails to bring up wwan. The sim will only come online after rebooting the device 10-15 times. I've rolled back the version of tch to `2023.05.16` which fixes the issue and allows the sim to come online on each reboot.

`Mon Jan 22 21:49:48 2024 daemon.notice wansensing: L2Main.lua: check interface PHY type nil
Mon Jan 22 21:49:48 2024 daemon.notice wansensing: mass failover protection, mobiled data timer is set, will wait 0.679 seconds (random in the range [0,10]) before interface 'wwan' ifup
Mon Jan 22 21:49:49 2024 daemon.notice wansensing: mass failover protection, mobiled data timer is timeout, interface 'wwan' ifup
Mon Jan 22 21:49:49 2024 daemon.notice netifd: Interface 'wwan' is setting up now
Mon Jan 22 21:49:50 2024 daemon.warn mobiled: Data session setup attempt for PDN 0 failed with error "Network failure"
Mon Jan 22 21:49:50 2024 daemon.debug mobiled-netifd[13921]: Queuing teardown action on interface wwan
Mon Jan 22 21:49:50 2024 daemon.debug mobiled-netifd[13921]: Running teardown action on interface wwan`

i have attached the full log file
[messages.log](https://github.com/seud0nym/tch-gui-unhide/files/14077999/messages.log)

**Comment by seud0nym** [comment]
I can't see any reason why tch-gui-unhide would cause that problem. If anything, I would have thought that `2023.05.16` could have caused an issue, because I changed the way VoLTE was configured. Apart from that, there are very, very few configurations that tch-gui-unhide changes - what it does is provide the mechanism to change configuration _yourself_.

I assume you have configured the Mobile Operator and Profile correctly on both implementations?

Can you compare the configuration from both the working system and the non-working system? You would need to run the following command in each:
```
uci show | sort > $(transformer-cli get rpc.gui.UnhideVersion | cut -d' ' -f4).txt
```
and then once you have copied both .txt files from `2023.05.16` and `2023.12.21` to your PC, use something like WinMerge or an online file difference tool to find the differences between the 2 files.

Otherwise, I am going to have to try and replicate your environment on my test DJA0230. Can you tell me:
* Did you reset to factory defaults between upgrading/downgrading tch-gui-unhide?
  * If yes, did you use the reset-to-factory-defaults script and what options did you use?
* Did you run de-telstra? If yes:
  * Which version?
  * Did you re-run when changing tch-gui-unhide versions?
  * What options did you use?
* What options did you use when running tch-gui-unhide?

The problem will be that I don't have a non-Telstra SIM to check. I only have AldiMobile or Boost SIMs.
