### ISSUE TITLE
Adding the LAN interface in the ‘Local Network Card’ 

### ISSUE THREAD

**Issue by bravohe** [seud0nym/tch-gui-unhide#192]
Device:DJA0231
Firmware:20.3.c.0389-MR20-RA
tch-gui-unhide Version:2024.02.29@17:16

I used the Web GUI to add a LAN interface in the ‘Local Network Card’ and then verified it with the terminal command ‘brctl show’ to check if the interface was correctly created. However, it didn’t show any new interface.”

file: /etc/config/network
config interface 'lan3'
	option proto 'static'
	option force_link '1'
	option rpfilter '1'
	option ip6hint '4'
	option ipv6 '0'
	option ip6assign '64'
	option netmask '255.255.255.0'
	option ipaddr '172.23.3.54'
	option auto '1'

**Comment by seud0nym** [comment]
It doesn't look like you have assigned any LAN ports to your interface. The interface won't be instantiated until you unassign at least one LAN port from the default LAN and assign it to your new interface. 

It will still then only show up in `brctrl show` if you assign _more_ than one port to the interface. A single port is not a bridge.

**Comment by bravohe** [comment]
Thank you for the update! It seems that despite following your instructions, the new bridge interface hasn’t appeared. 

By the way, I didn't enable Vlan filter yet.

file: /etc/config/network
config interface 'lan3'
	option proto 'static'
	option force_link '1'
	option rpfilter '1'
	option ip6hint '1'
	option ipv6 '0'
	option ip6assign '64'
	option netmask '255.255.255.0'
	option ipaddr '172.23.3.54'
	option ifname 'eth2'
	option auto '1'

**Comment by seud0nym** [comment]
You haven't created a bridge, so it will never appear.

As I said, a bridged interface only exists when there are two or more physical interfaces combined into one logical interface. You only have added 1 physical interface (eth2) to your logical interface (lan3) so there is no bridge. It is a single port interface.

A single port interface is not listed in brctrl, because that only shows bridged ports.

**Comment by bravohe** [comment]
Device:Technicolor DJN2130
Firmware: 17.2.0284-820-RA
tch-gui-unhide Version:2024.02.29@17:16

I used my backup modem to try VLAN setup but I got error message as below:

Failed to set uci.firewall.zone.@6.name to 'test2': invalid path uci.firewall.zone.@. (9005)
Failed to add new section to 'uci.firewall.zone.@6.network.': invalid path uci.firewall.zone.@.network.

![Screenshot 2024-03-14 at 10 00 51 am](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/aecbfa0b-85aa-4004-b9ff-dc3cf683cbc0)

**Comment by seud0nym** [comment]
It looks like 17.2.0284 handles paths differently to 17.2.0468 (which is what I tested on, because I don't have a DJN2130) and later.

First, are you really, really, _really_ sure you want to use 172.40.2.57? That is a real, routable, **public** internet address that should never, ever be used in a LAN.  I would _strongly_ recommend that you do not use it.

The class B IPv4 addresses reserved for private use are from 172.16.0.0 to 172.31.255.255. This range is not routable on the internet. All 172.x.x.x addresses outside of this range are routable over the internet.

Second, you need to clean up the stuff that it couldn't roll back when it encountered the error with these commands:
```
transformer-cli del uci.firewall.zone.6.
transformer-cli apply
```

Third, I have fixed that bug and you can apply the update with this command:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```
```

**Comment by bravohe** [comment]
Thank you for your advice. I have removed the 172.40.x.x network. VLANs work well now, but I don't understand why I can't have one physical interface (eth2) connected to my logical interface (lan3) with bridge. For example, I would like to have a trunk port on my logical interface (lan3).

Thanks a lot.

**Comment by seud0nym** [comment]
If you want to call it a bridge, then just go into /etc/config/network and add `option type 'bridge'` under `config interface 'lan3'` and then restart networking.

I am not a networking expert, but I think the logical interface is a trunk port by default anyway, bridge or not.
