### ISSUE TITLE
set-optimal-bank-plan file missing in 20.4 tar file?

### ISSUE THREAD

**Issue by tennis888** [seud0nym/tch-gui-unhide#198]
Downloaded 20.4.tar.gz and found that file set-optimal-bank-plan is missing?
Trying to run it on a Telstra Smart Gen 3. 
"set-optimal-bank-plan" not needed to run on Gen 3 router?

root@mymodem:/tmp/run/mountd/sda1/20.4# tar -zxvf ../20.4.tar.gz 
tch-gui-unhide
tch-gui-unhide-20.4
tch-gui-unhide-cards
de-telstra
dumaos
guest-restore
hijack-dns
log-check
mtd-backup
mtd-restore
overlay-restore
ptree
reboot-on-coredump
reset-to-factory-defaults-with-root
safe-firmware-upgrade
set-web-admin-password
show-bank-plan
unflock
update-ca-certificates

**Comment by seud0nym** [comment]
`set-optimal-bank-plan` does not work on a Gen 3, mainly because the bank sizes are different, so it is not possible to copy the firmware between banks like you could on previous generations. Also, it is not possible to write a firmware into a mounted bank like you could on previous device.

You have to do it manually on a Gen 3. My suggested approach is:

1. Ensure you have a rootable firmware in bank 1
2. Ensure you are running from bank 1
  a. Use `./show-bank-plan` to see active/booted bank
  b. If necessary, swap to bank 1 using `./reset-to-factory-defaults-with-root -s`
3. Use `./safe-firmware-upgrade` to load required firmware into bank 2
  a. This will automatically reboot into bank 2
4. Confirm bank layout with `./show-bank-plan`

When you want to upgrade firmware on a Gen 3, I recommend switching back to the rootable firmware in bank 1 with `./reset-to-factory-defaults-with-root -s` and load the new firmware into bank 2 with `./safe-firmware-upgrade`.

Since you are currently on 20.4, I would *strongly* recommend having 20.4 in bank 1, and load the latest 21.4 (which is not rootable) into bank 2.

**Comment by tennis888** [comment]
Ok thank you
