### ISSUE TITLE
Idea for Internet Access card

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#20]
I was thinking about this for the last few days, since we can go in the card and change DNS ourselves but it would be cool to display the "DNS Server" on the Internet Access card via the GUI so that way if we come to the router page, we can see what DNS servers is being set as. So if they are using ISP DNS, it would show the ISP dns on there, unless they manually set the dns servers. Of course we still have to change DNS by going inside it. But displaying what DNS server being used is helpful too.

See picture of the idea;
![dns](https://user-images.githubusercontent.com/45726972/104140535-7c2bab00-53fd-11eb-80ed-62da5ff1226e.png)

Again, its up to you. Would be nice to display DNS info on there 👍 

EDIT: Changed/Replaced the image of the IPv6 DNS.

**Comment by seud0nym** [comment]
Thanks for the suggestion.

I have had a look at this, and the problem is that you can only fit 5 lines, and maybe 6 with some squishing, on a card. If you have an IPv6 address assigned, 4 lines are gone on the card, which would leave max 2 available. Given the length of IPv6 addresses, that is not enough room. You could even run out of room with IPv4 addresses: your custom addresses are really short, but, for example, the OpenDNS FamilyShield servers are 208.67.222.123 and 208.67.220.123, which probably would not fit on 1 line. 

I could easily add a single line that showed the number of servers and whether you are using auto-discovered DNS (i.e. ISP assigned) or custom DNS.

It might be possible with a bit of squishing to fit them on the IP Routing card (which currently shows the number of DNS servers) e.g. remove the count and list the actual servers.

What are your thoughts?

**Comment by jmytch** [comment]
Umm, that could work and I was thinking, as you can see I've disabled WAN Sensing, maybe it would be ideal to hide that for those who disabled it then there would be plenty of lines for the DNS IP Addresses wouldn't it? If not, then your idea could work too :)

**Comment by seud0nym** [comment]
Okay, so what I have done is moved the L3 WAN sensing status from the Internet card to the Broadband card (which I think is where it should be anyway, since you can only change WAN Sensing through the Broadband card). That has freed up enough space. This is what it looks like (dark theme and I have IPv6 enabled):

![image](https://user-images.githubusercontent.com/41851175/104673186-507a2f00-5735-11eb-87f2-e6acbfb23e60.png)
