### ISSUE TITLE
Custom pages?

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#28]
What does "--pretranslated: do not change this file" mean?
How would one go about writing their own CSS/HTML for, say, the landing page?
I understand most of the code for that is stored in "landingpage.lp" and have managed to make basic customizations to it, but I was wondering if you passed html through some sort of "compiler" that turned it into this "translated" code?

**Comment by seud0nym** [comment]
I assume (and I could be wrong) that there is some processing done when Technicolor make their releases so that they can build for multiple languages, and it is just a reminder to developers not to change the built code. As I said, I could be wrong.

No, I don't do anything special. I just apply edits to the files as they are. No post-processing or compiling step.

The only thing to watch out for is that sometimes it may appear that your edits are not being picked up. If that happens, restart nginx with this command: ```/etc/init.d/nginx restart```

If you have some shell scripting skills as well as CSS/HTML, you can make sure that your changes stick after upgrading tch-gui-unhide by wrapping them up in your own "xtra" script (have  a look at https://github.com/seud0nym/tch-gui-unhide/tree/master/extras for some examples). Your script just has to be named **tch-gui-unhide-xtra.**_whateveryouwant_, and exist in the same directory as tch-gui-unhide. The only thing to be aware of is that, in the current release, xtra scripts are executed _after_ normal tch-gui-unhide processing, but from the next release, they will be applied _before_ other processing. I am making that change because it will allow me to create xtra scripts that add new cards to the interface.

**Comment by SmartBoy84** [comment]
In that case, respect man. I had difficulty even making the most basic of changes.
Thanks for all your hardwork!

**Comment by seud0nym** [comment]
> What does "--pretranslated: do not change this file" mean?

If you are interested, I did eventually find out what this means. It flags the file as already being pure LUA, so there is no pre-translation step when compiling the file to convert it into LUA code. Without this flag, I think it gets processed twice: once to convert any older style markup into LUA code, then a second time to compile it for execution.
