### ISSUE TITLE
ipv6 hostname

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#32]
how do i go on fixing the ipv6 hostname? 

i tried googling it but couldnt find what i want. i tried searching openwrt ipv6 hostname 

![Capture](https://user-images.githubusercontent.com/45726972/123529675-fe9ef180-d735-11eb-9d2e-11115c65ee70.PNG)

**Comment by seud0nym** [comment]
It is controlled by your ISP, since IPv6 addresses (except for the non-routable ones, of course) are global by their nature.

I am with Superloop and they do have hostnames for IPv6 addresses, but they are 20 character almost random names.

Also, not all IPv6 addresses are obtained via DHCPv6. Some are assigned by SLAAC (StateLess Address Auto-Configuration) so there is no DHCPv6 server involved to create a PTR record in the DNS server.

**Comment by jmytch** [comment]
Yeah never mind, called Exetel and they said they don't. Thanks anyway
