### ISSUE TITLE
New card - VPN?

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#34]
Wonder if can have new card called VPN where we can input ip address, configuration into VPN card so that VPN is at the router level where all devices go through the VPN?

**Comment by seud0nym** [comment]
Just before the 20.3.c firmware was released and I got side-tracked into creating the release to support that, I was working on VPN configuration.

The first stage will be to configure the device as a VPN Server (so you can access it remotely). That is the easier bit, because there is a bit of documentation around on how to do it.

What you are talking about is a second stage, where you can connect your device to a VPN service as a client. This appears to be much more tricky, and there isn't a lot of information I have found.

You have to be aware that there will be limitations (if I can get it working). There are no OpenVPN or WireGuard packages for these devices. We are limited to strongswan and therefore IKEv1, IKEv2 or L2TP protocols (and I probably won't look at L2TP).

It's on my list...

**Comment by jmytch** [comment]
Ah, the VPN I was looking at is using WireGuard https://mullvad.net/en/

**Comment by seud0nym** [comment]
I am using mullvad. It is great on my PC, but no, at this stage it doesn't look like you can run it on a DJA0230/1.

The other problem with these devices is that they cannot do IPv6 NAT, which means that you are limited to an IPv4 VPN only, and if you do use IPv6, then your real IPv6 address gets leaked. It is why I chose mullvad for my PC - it is one of the few that supports IPv6 properly.

**Comment by jmytch** [comment]
Yeh don't worry about this. I guess it was just an idea lol.

**Comment by seud0nym** [comment]
I am keeping this open in case anything changes.

**Comment by seud0nym** [comment]
I have just released an extras script that you can use to configure WireGuard on your DJA0230. I have posted some more information on Whirlpool:

https://forums.whirlpool.net.au/thread/9vw4mwyn
