### ISSUE TITLE
ECO - add info

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#35]
Could you please add (?) where we can hover over to as to what it does for `Network Device Down` and `PHY Power Down` please?

I enabled Network Device Down, not knowing what this does, and it cut my ethernet out as couldn't revert it back so had to use my mobile to get on PuTTY (alternative app) on Android to disable it. 

Tried enabling PHY Power Down, same result as above, I don't know what they are as it seems new to me as never seen them before. Tried searching up the `Network Device Down Ethernet` and it doesn't say anything about it? It's abit strange.

EDIT:
Also I noticed CPU Power is not in ECO Settings anymore? I don't know if mine is set on Auto-Scaling or is still 100% ASYNC?

**Comment by seud0nym** [comment]
I will add an alert box above them that says to be careful because they power down network interfaces.

The CPU control settings and a lot of other settings now report N/A (I assume Not Available or Applicable). Turning them on or off seems to work, but then showing the settings again still reports N/A. 

Here is the output from showing current settings and and changing the CPU Speed option:
```
root@DJA0230:~# pwrctl show
WIFI Off            N/A
DISK Off            N/A
PCI ASPM            N/A
UBUS DCM            N/A
CPU Off             N/A
CPU Wait            N/A
CPU Speed           N/A
XRDP Gate           N/A
NET Down            Disabled
PHY Down            Disabled
PHY EEE             Enabled
PHY APD             Enabled
SF2 DGM             Enabled
DRAM SR             N/A
AVS                 N/A
WLAN Down           N/A
PMD Off             N/A
root@DJA0230:~# pwrctl config --cpuspeed on
CPU Speed (*) ==> Enable
root@DJA0230:~# pwrctl show
WIFI Off            N/A
DISK Off            N/A
PCI ASPM            N/A
UBUS DCM            N/A
CPU Off             N/A
CPU Wait            N/A
CPU Speed           N/A
XRDP Gate           N/A
NET Down            Disabled
PHY Down            Disabled
PHY EEE             Enabled
PHY APD             Enabled
SF2 DGM             Enabled
DRAM SR             N/A
AVS                 N/A
WLAN Down           N/A
PMD Off             N/A
```

As you can see, even though the response to turning it on says that it is Enabled, show the current settings again gives N/A.

So my assumption is that they have either removed the ability to control those CPU power functions, or maybe that they never worked anyway!
