### ISSUE TITLE
5 G won't show on repeater unit 

### ISSUE THREAD

**Issue by Agentfox2019** [seud0nym/tch-gui-unhide#41]
Run the latest version and the booster is not receiving the SSID for the 5g wireless network
2.5g is working fine.

**Comment by Agentfox2019** [comment]
got to save
![wireless](https://user-images.githubusercontent.com/89790248/131353287-8d0ed01a-0783-4a5a-bd98-6ef4b6ea2d4f.PNG)

**Comment by seud0nym** [comment]
Sometimes after first boot it doesn't pick up the SSID. On the booster device, try disabling and then re-enabling the agent. Wait a minute or 2 and it should be propagated correctly.

**Comment by Agentfox2019** [comment]
It's now showing up as an SSID in the booster but not broadcasting the Wifi on 5g

**Comment by seud0nym** [comment]
There should not be anything in the re-configuration that would prevent the WiFi from working.

My only suggestion would be to do a factory reset, ensure the WiFi is working correctly, and then re-apply the scripts.

**Comment by Agentfox2019** [comment]
The flashed Unit was working fine with 5g before the upgrade.

I have power cycled both units and the 5g is no longer showing on any unit now 

![image](https://user-images.githubusercontent.com/89790248/131475108-f28e026d-14a9-465f-8151-836677c9a9f6.png)

**Comment by seud0nym** [comment]
All the scripts do is disable anything WAN related, set the device in bridge mode (which again is about making the device part of the LAN only), and add the wifi interfaces into the LAN bridge and the multiap configuration. It doesn't do anything else to the wifi. It certainly doesn't disable either wifi band.

It is strange that it is showing that only 1 SSID has been synced. I have never seen that happen on the booster after restarting the agent. 

The only suggestion I would make is to remove spaces and the . at the end from your SSIDs. Another user on the Whirlpool forums reported that a problem they were experiencing on these devices was resolved when they removed special characters from their SSID.

Otherwise,  my suggestion still stands: RTFD and try again. But if it isn't working for you, I am not sure what else I can advise.

**Comment by Agentfox2019** [comment]
Changed the SSID on the 5G 
![image](https://user-images.githubusercontent.com/89790248/131486409-f4a290f0-d4c1-4ab6-8583-5558a39a6e32.png)
But no visible connection via the booster on 5G

**Comment by seud0nym** [comment]
If you do a Google search, there are various issues around using spaces in your SSID. The general consensus seems to be: Don't
