### ISSUE TITLE
Configured Custom DNS entries does not impact wwan interface

### ISSUE THREAD

**Issue by kk246** [seud0nym/tch-gui-unhide#47]
As per title.
Custom DNS entries within the "Internet Access" card

**Comment by seud0nym** [comment]
I have had a bit of a look at this. Copying across the IPv4 DNS Servers doesn't seem to be a problem, but for IPv6 it uses a non-configurable pseudo-interface. Since the default backup SIM configuration is IPv6 only, it is an issue.

I have some ideas, and will keep looking at it.

**Comment by seud0nym** [comment]
A bit of background: the Internet Access screens were imported from the Ansuel custom GUI, tidied up a bit and enhanced to suit my needs. Custom DNS servers were defined on the network interfaces themselves. However, on the Hacking Technicolor site, it says that the correct way to define custom DNS entries is to apply them through dnsmasq (rather than the individual network interfaces).

So, I have completely reworked custom DNS Servers. I have moved DNS Servers from Internet Access to a new card, and migrated custom DNS servers configured on network interfaces to dnsmasq, so that custom DNS servers are applied consistently across all connection modes (including mobile connections).

This will be in the next release.
