### ISSUE TITLE
Download shaper

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#48]
Just like the Upload Shaper in the QoS, is it possible to add Download Shaper to specific mac address of the device? Kinda sick of all the bandwidth hogging and would be nice to limit download shaper on specific devices at the router level.

**Comment by seud0nym** [comment]
Looks like it might be possible:

https://github.com/griggi/openwrt-fair-bandwidth-distributor
https://openwrt.org/docs/guide-user/network/traffic-shaping/packet.scheduler.example2

The second link talks about upload, but looking at the first one, replacing the WAN device with the LAN device (br-lan) turns it into a download shaper.

I had a quick look and it looks like the HTB packet scheduler **_is_** available on our devices (at least on my test DJA0230 which currently has 20.3.c.0389 on it).

I am working on something else at the moment, but I will look at it soon.

**Comment by jmytch** [comment]
Yeah no problem at all, and just do your thing first before doing this one. Yeah I'm on the latest firmware of 20.3.c.0389 too on the DJA0230 :-) 

If the first link is gonna be added, I suggest adding them inside the QoS next to Upload Shaper if possible. Just saying, anyway take your time.

**Comment by seud0nym** [comment]
Actually, this example looks like _exactly_ what you want to do:

https://openwrt.org/docs/guide-user/network/traffic-shaping/packet.scheduler.example5

**Comment by seud0nym** [comment]
It is a shell script - the easiest way would be put them into `/etc/rc.local` (leave out the `#!/bin/sh` and `insmod` lines) before the `exit 0` line. That will make sure it is executed on every reboot.

Or, you could wait for me to add it to tch-gui-unhide... :-)

**Comment by jmytch** [comment]
> Or, you could wait for me to add it to tch-gui-unhide

I think I'll just wait as it would be better :-)

**Comment by bones-was-here** [comment]
It might be possible to run the OpenWrt SQM package using fq_codel, DJN2130 has the required kernel modules.

**Comment by seud0nym** [comment]
All the examples I have found so far use the HTB packet scheduler when applying shaping to a subset of devices. 

The problem I have come across is that when I applied shaping based on MAC address, it worked fine for wired devices, but I had problems with wireless devices. My Android phone uses a randomised MAC by default, which was the first problem, so that means that MAC based shaping can be easily by-passed. The second issue was that applying the shaping on the lan bridge (to cover both the ethernet ports and wireless interfaces) again worked for wired devices but seemed not to work for my phone (even though I had turned off MAC randomisation). 

Still working on it...

Just as an aside though: my reading has led me to the understanding that scheduling happens on packet _egress_, which means that when you apply a shaper to a WAN interface, it shapes uploads, but for LAN/WLAN interfaces, it will shape downloads! I have already changed the wording on the traffic shaping tab in tch-gui-unhide to reflect this (for then next release).

For the DJN2130, download this:
https://archive.openwrt.org/chaos_calmer/15.05.1/bcm53xx/generic/packages/base/tc_4.0.0-1_bcm53xx.ipk
I couldn't get the package to install (even by adding arch bcm53xx to /etc/opkg.conf), but I was able to manually extract the `tc` command from the ipk and copy up into the /usr/sbin directory (don't forget to make it executable with `chmod +x /usr/sbin/tc`).

**Comment by jmytch** [comment]
Umm if that is still a problem, then maybe adding other option to use LAN IP address of the device? Or if you use LAN IP address where it picks up the MAC Address Randomization?

**Comment by seud0nym** [comment]
Using the IP address actually makes it much more complicated. If it was just IPv4 it wouldn't be too bad, but I need to make it work for IPv6 as well, and each device can have _lots_ of IPv6 addresses...

Anyway, I found the problem I was having: The packet.scheduler.example5 script has a default filter that is supposed to apply to everything else. I found if I had that defined, the wireless devices wouldn't get the shaping applied. When I removed it, it worked fine.

So, making progress...

**Comment by seud0nym** [comment]
Done and ready for the next release.

Example screen shot of the new tab:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/41851175/144183055-d9dc675d-269e-4c37-bded-1a6ee3195dd0.png">

**Comment by jmytch** [comment]
Awesome, looking great and good job :) 

Just to double check, it does shape bandwidth over WiFi now?

**Comment by seud0nym** [comment]
Yes, everything seems to be working correctly.

**Comment by bones-was-here** [comment]
HTB is very old but still useful for limiting throughput, both per-connection and per-service or per-device.

Within each HTB class some way to manage the packet queue is needed, when the class is operating at it's bandwidth limit.  By default this is a simple FIFO which will cause rather bad latency when a 'bulk' service and a 'low latency' service are operating in the same HTB class.  The traditional (early 2000s wondershaper) choice is SFQ, it's better than a FIFO but these days we can do much better by using fq_codel.  fq_codel automatically distinguishes between different types of services, and allows latency targets to be configured and small packets to be prioritised.

Personally I do not rely on per-device bandwidth limits, partly because devices can change address and/or have multiple addresses and with many devices it quickly becomes a pain.  But also, because I often want to run bandwidth-heavy programs and latency-sensitive programs on the same PC at the same time.  
On the DJN2130 I have achieved great results using a single HTB upload and download class for the connection (to limit the total speed, keeping the queue on my router where I can control it), and managing those queues with fq_codel.  I can run multiple uploads and downloads at nearly the full speed of the connection with little to no impact on pings in games (all on the same PC, or on separate devices).

fq_codel doesn't automatically handle the case where one program opens a thousand connections simultaneously.  That (and many other) improvements are included in CAKE, which replaces both HTB and fq_codel and builds on many of the ideas implemented in fq_codel.  CAKE is included in kernels >= 4.19 and unfortunately does not compile against 3.4.11-rt19.

Shaping downloads at egress from a LAN interface works fine in simpler configs, on a dedicated router with no other services, but is not so good on routers carrying wifi<>lan traffic and when the router may provide LAN services such as file sharing with a USB HDD.  For this reason Linux includes the Intermediate Functional Block, a virtual network interface that download traffic may be forwarded through.  HTB and fq_codel can then be enabled on the IFB device, the same as would be done with uploads on the WAN interface.

The `tc` package you linked installed cleanly (and works) on my router, once I appended `arch bcm53xx 40` to /etc/opkg.conf

These routers don't have a strong enough CPU to shape 500mbps or 1gbps connections, they can handle these speeds only when the bulk of the traffic is bypassing the CPU.  The DJN2130 CPU can easily handle 100mbps, and maybe 250mbps.

**Comment by seud0nym** [comment]
I am glad you were able to get the `tc` package installed. I did the add the same to my /etc/opkg.conf but it failed to work for me. Strange.

It seems like you know what you are talking about with this stuff. I am more 'copy-and-paste' when it comes to this level of networking configuration.

If you didn't have `tc`, how were you able to configure your classes and queues?

Anyway, yes, I am using ifb to add handle ingress. I am applying the config to br-lan (and br-lan-ifb after I create it). This is the setup for an example 50/20 connection:
```
tc qdisc add dev br-lan root handle 1: htb r2q 50
tc class add dev br-lan parent 1: classid 1:1 htb rate 50mbit
	
ip link add dev br-lan-ifb name br-lan-ifb type ifb
ip link set dev br-lan-ifb up
	
tc qdisc add dev br-lan-ifb root handle 1: htb r2q 50
tc class add dev br-lan-ifb parent 1: classid 1:1 htb rate 20mbit
	
tc qdisc add dev br-lan ingress
tc filter add dev br-lan parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev br-lan-ifb
```

To use fq_codel instad of htb, is it as simple as replacing the scheduler name in the `tc class` command? 

e.g. what I have now to create a class with a 20/5 cap is:
```
tc class add dev br-lan parent 1:1 classid 1:11 htb rate 20mbit ceil 20mbit
tc class add dev br-lan-ifb parent 1:1 classid 1:11 htb rate 5mbit ceil 5mbit
```
Do I just do this instead?
```
tc class add dev br-lan parent 1:1 classid 1:11 fq_codel rate 20mbit ceil 20mbit
tc class add dev br-lan-ifb parent 1:1 classid 1:11 fq_codel rate 5mbit ceil 5mbit
```

**Comment by bones-was-here** [comment]
I used a PC to cross compile tc for the router.

I recommend changing the download shaper to forward to the IFB from the WAN interface (eth4 on my device), instead of from the lan bridge.  Currently you will be shaping lan traffic, so any download speed limit would apply to a USB HDD plugged into the router (and possibly to wifi<>ethernet traffic, not sure).

fq_codel can't do rate limiting (CAKE can) so you would still need the HTB class to do that.  A HTB class has no scheduler by default (it's just FIFO), so you need another command to add one (which can optionally tune that scheduler somewhat).

Eg: `tc qdisc add dev ifb0 parent 1:11 fq_codel`

**Comment by bones-was-here** [comment]
Might be worth noting that by default an IFB has `txqueuelen 32` which will have rather awful throughput at higher line rates, if a scheduler is not added that has it's own (longer) queue (fq_codel has a Big default queue).  This is because it's assumed that the IFB is being added for the purpose of applying some scheduler to incoming traffic.

**Comment by seud0nym** [comment]
So based on your suggestions, I should:

- Not use `br-lan`, but work out the WAN interface device and use that (i.e. eth4, ptm0, or atm_8_35).
- Create the IFB on that same WAN interface, but make the `txqueuelen` either the same as the WAN interface (seems to always be 1000?)
- Add the fq_codel scheduler to each HTB class I create

Also, as I was looking around, and noticed this:
https://openwrt.org/docs/guide-user/network/traffic-shaping/packet.scheduler#filter_with_packet_scheduler
Under the Notes, it says: **`packet scheduler` classifying is slower then `netfilter `classifying!**

Do you have an opinion on that, and if it is true, should I replace my `tc filter` commands with `iptables`/`ip6tables` equivalents? (They would certainly be easier to read than the `tc filter` commands!)

**Comment by seud0nym** [comment]
Left it on br-lan using `tc filter`, but implemented `txqueuelen` change and added `fq_codel` scheduler on each new class. I have added a warning message about the impact on services such as File Sharing, and potential CPU/bandwidth limitations.

In latest release (2021.12.06) available now
