### ISSUE TITLE
feature request: GUI option to make static hostnames always resolve

### ISSUE THREAD

**Issue by bones-was-here** [seud0nym/tch-gui-unhide#52]
When a static DHCP entry with a hostname is created, the hostname can only be resolved while the device has an active lease for the assigned IP.  Sometimes this is fine, but certain operating systems will never retry print jobs if they can't resolve the printer's hostname because it's turned off or still booting up.  There's also devices that don't use DHCP at all but for which it would be nice to have a DNS entry.

Some router firmwares (eg freshtomato) always resolv hostnames for static leases, by default.

In openwrt this can be achieved at the CLI with:
```
uci set dhcp.@host[0].dns=1
uci commit
/etc/init.d/dnsmasq restart
```

**Comment by seud0nym** [comment]
Here is what it looks like:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/41851175/144548220-09bf8266-1983-4731-830e-05bf6efc6aa1.png">

Hovering over the question mark shows: _Add static forward and reverse DNS entries for this host, so that the host name resolves even when lease is not active._

**Comment by seud0nym** [comment]
In latest release (2021.12.06) available now.
