### ISSUE TITLE
Disable local domain name

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#61]
Would we be able to turn off or have a button to disable the local domain name in the local network tab?

**Comment by seud0nym** [comment]
I only added that field in release 2021.05.09. I guess I would need to understand the rationale for such a feature. 

Turning off individual fields isn't really complex, but my concern would then be how many switches I would need to allow other fields to be turned off on request, and that becomes a larger issue.

**Comment by gyCfjSnO** [comment]
Ideally I want to stop local domain queries going to my DNS

**Comment by willat8** [comment]
If you're using pihole, you can hand out the pihole DNS to DHCP clients, then configure the pihole upstream DNS back to the DJA0230 (not sure this applies to your setup)

**Comment by seud0nym** [comment]
Sorry, I misunderstood your requirement.

As [willat8](https://github.com/willat8) said, can you configure your DNS to do what you want? AdGuard Home has the same sort of configuration as Pi-hole to allow local domain queries to be handled by the router.

**Comment by gyCfjSnO** [comment]
I was hoping that if I disable or blank out the local domain name then it would stop sending the queries to my DNS

**Comment by seud0nym** [comment]
The router isn't sending those queries to your DNS Server. It is the client machines on your LAN sending queries to your DNS, because that is what you told them to do by setting the DNS Server on the DHCP settings (or via interception). If you remove the domain, instead of devices getting a name like 'MyPC.gateway' or 'MyPC.modem" (whatever you have set your domain to), it would just be 'MyPC.' It won't stop a lookup happening to the DNS server to find an IP address for a device. 

You need to configure your DNS Server to send queries for your domain back to the router to be resolved.

Unless I am still not understanding your issue...

**Comment by gyCfjSnO** [comment]
I thought removing the field or disabling would stop the issue but seems to not be related and is a seperate issue that's a me problem. Closing as no further action required.
