### ISSUE TITLE
Merge with tch-nginx-gui?

### ISSUE THREAD

**Issue by FrancYescO** [seud0nym/tch-gui-unhide#64]
@seud0nym do you think there is a possibility to have these project merged? https://github.com/Ansuel/tch-nginx-gui
in my opinion the main goal should be to have a GUI that is working cross-firmware (also backporting functionalities where possible) and cross-ISP customization, and i love your patch-oriented way...

But as you are keep going over with this good work in forked-way let me know if you are interested in a somehow merge...

**Comment by seud0nym** [comment]
Thanks for getting in touch, and I apologise for taking some long to respond.

The code patching approach works for a lot of things, and I think it helps with stability and not interfering with features that might be found on one device and not another. I have found that if the patch script gets too large, it is better to just include the modified file and then maybe patch that if required. BUT, I am only dealing with 3 firmware versions and 1 ISP, but I guess the overall structure could be adapted for multiple ISPs.

Everything is controlled by a single build script that uses the directory structure and some specially named files to work out what is to be concatenated into the firmware script. The build is not particularly clever or elegant, because it has just evolved over time.

One thing that I think might be a major difference between the projects is that my GUI patching code only deals with patching the GUI and adding new features. Changing configuration and hardening the device against root loss is handled by utility scripts, because some of my users don't want to apply that level of customisation. They only want to get access additional features in the GUI without breaking anything that Telstra has applied to the device. 

I am happy to discuss merging the projects. I will be guided by you whether you think it is feasible because tch-nginx-gui supports a lot more devices and firmware than tch-gui-unhide.

**Comment by FrancYescO** [comment]
Breaking is also something that also tch-nginx-gui does not want to do, but the main issue i've found and we got over time is the support of as-much-we-can firmwares and devices, often backporting things on older devices... to have this things done there is a main reason that i assume fastly break things, and is the full replace of /usr/share/transformer/mappings/ but we can progressively think to patch the needed files istead of embedding/replacing all 

As a first approach we can think that tch-nginx-gui can be applied by who want to get the full features, while tch-gui-unhide only for "unhide", in both case ISP's things must work, unfortunately for us is pretty difficult to debug things on devices that we don't have so in general this collaboration can start from just "fix things that tch-nginx-gui breaks", i think tch-nginx-gui really needs another dev that will take care that all will keep working on all Telstra models, and seeing that all this good work is splitted makes me sad :D

**Comment by seud0nym** [comment]
I sometimes wish that I had not called it 'tch-gui-unhide'. It seemed logical at the time, because all I was doing was showing the cards and modals that were hidden by Telstra. But it is so much more now: I have borrowed some of the stuff from tch-nginx-gui, but I have also added lots of features that I don't think even appear in tch-nginx-gui.

The stumbling block as I see it is that I don't really want to start porting Telstra features into tch-nginx-gui. For example, the most obvious place to start is with /www/docroot/modals/wireless-modal.lp. Your version is almost 2000 lines; the latest Telstra version is almost 2200 lines.  I would need to compare line by line and try and work out what extra things that Telstra has done, and not break any of your edits. And things like band steering are really complicated on the Telstra boxes, because of the interaction with EasyMesh.

With the tch-gui-unhide approach, I worked out the few edits I needed, which boiled down to 36 lines of code, one-third of which is the output power list. And it works against the 17.2, 18.1c. and 20.3.c firmware, with and without EasyMesh.

**Comment by gyCfjSnO** [comment]
As a user of this project I feel they're two seperate projects, one of which just works with the Telstra modems and has a lot of customised scripts that benifit Australian users and are not included in Ansuel.

**Comment by willat8** [comment]
> As a user of this project I feel they're two seperate projects, one of which just works with the Telstra modems and has a lot of customised scripts that benifit Australian users and are not included in Ansuel.

I agree. As someone who randomly wondered one day if my Telstra modem could be rooted, I came across the hack-technicolor docs. They referenced tch-nginx-gui which seemed like a logical next step but turned out to be really buggy. It was only after reading deep on Whirlpool that I came across tch-gui-unhide.

It sounds like a huge amount of work to merge the projects, but perhaps they could live side-by-side in the same repo somehow? Would simplify the hack-technicolor pathway.

**Comment by FrancYescO** [comment]
> added lots of features that I don't think even appear in tch-nginx-gui.

Probably this is just the main reason about asking for this merge, if you think added something that can be useful for all just add it also to tch-nginx-gui :P

> the most obvious place to start is with /www/docroot/modals/wireless-modal.lp. Your version is almost 2000 lines; the latest Telstra version is almost 2200 lines. I would need to compare line by line and try and work out what extra things that Telstra has done, and not break any of your edits. And things like band steering are really complicated on the Telstra boxes, because of the interaction with EasyMesh.
> 
> With the tch-gui-unhide approach, I worked out the few edits I needed, which boiled down to 36 lines of code, one-third of which is the output power list. And it works against the 17.2, 18.1c. and 20.3.c firmware, with and without EasyMesh.

Keep in mind that more or less tch-nginx-gui does the same, the wireless-modal.lp and probably the one from lan are the worst thing around but the edits to the final tch-nginx-gui file is just the original file from an old homeware firmware (probably 16.x from TIM) with few line of patches needed to have it working on all devices and firmwares, but actually this is something that needs to be reworked as we need to embed the easymesh/multiap/bandsteeering things and this modal is surely not working on all devices as it comes from a very old base...


the first goal of tch-nginx-gui was to add mods for TIM ISP and Italians user (like you are doing for telstra)... on long term, looked as it was applicable more or less on all tch gateways (the core "ifs" are written in place from technicolor so often the code is portable on all devices) so it started to be an "unbranded mod for tch gateways", my goal actually is to just have merged anything that can help in a more general way any gateway user, than we can also think about a section where to add all ISP-related mod stuff

**Comment by seud0nym** [comment]
The way my repository is structured it should be really simple for you to copy in the cards, modals, etc. and then grab the configuration from the associated common build script.

- The DNS card and modals are all new, and should just work on any 17.2+ firmware. Just remove the DNS tables from your internet snippets. 
-  Same with the Packages card and modals. 
-  Telephony Dial Plan editor should just work, but I think there was also a change to the transformer mapping. It will be in the build script. 
- I have completely reworked QoS and Firewall with new tabs and features. 
- I did some reworking for IPV6 in the Internet snippets (especially static) but I have removed the ISP-specific stuff from them.

**Comment by gyCfjSnO** [comment]
> > As a user of this project I feel they're two seperate projects, one of which just works with the Telstra modems and has a lot of customised scripts that benifit Australian users and are not included in Ansuel.
> 
> I agree. As someone who randomly wondered one day if my Telstra modem could be rooted, I came across the hack-technicolor docs. They referenced tch-nginx-gui which seemed like a logical next step but turned out to be really buggy. It was only after reading deep on Whirlpool that I came across tch-gui-unhide.
> 
> It sounds like a huge amount of work to merge the projects, but perhaps they could live side-by-side in the same repo somehow? Would simplify the hack-technicolor pathway.

I personally feel like they're trying to get credit for someone else's hard work.

**Comment by seud0nym** [comment]
Sorry, I don't think that I am prepared to put in the effort required to do such a merge.
