### ISSUE TITLE
Logs still missing after upgrade

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#71]
Thanks for the recent release.
I upgraded via the web UI again but am still experiencing the behaviour where logs stop after the upgrade.

**Comment by seud0nym** [comment]
I have now noticed 2 distinct behaviours in the 20.3.c firmware:

1. The logread command shows messages up to a point in the past, and then stops. Messages are still logged to /root/log/messages.log
2. The logread command shows current messages, but messages in /root/log/messages.log stop at some point in the past.

In the past, I only saw number 1 happening and it can be fixed with `/etc/init.d/log restart` (which is what I added to the tch-gui-unhide install).

However, my main DJA0231 was exhibiting number 2 this morning. It seems to be working again now, after I did this:
```
/etc/init.d/lsyslogd stop
/etc/init.d/log stop
rm -f /var/run/luasyslog.pid
pgrep -f luasyslog | xargs -r kill -9
/etc/init.d/log start
/etc/init.d/lsyslogd start
```

**Comment by willat8** [comment]
Those steps also resolve for me the type 2 situation you describe.

**Comment by willat8** [comment]
It's looking good for me on 2022.03.01 now - thanks.

**Comment by willat8** [comment]
Logs have consistently stopped for me on my two DJA0230s running 20.3 over the last two upgrades (and possibly before that but I didn't check). Does maybe that second set of commands need to be added to the upgrade script?

**Comment by seud0nym** [comment]
I used to have a check in the install script to try and detect that logging was broken, but I removed in the 2022.08.20 version because it was unreliable.

I am guessing you are still on 20.3.c.0389? It is worth upgrading to 20.3.c.0432 - I haven't noticed the problem since I upgraded.

If you don't want to upgrade, the other thing you could do is get the old `logcheck` script (or you might still have it from an old release):
https://github.com/seud0nym/tch-gui-unhide/blob/2022.07.28/utilities/log-check

Run it with `./logcheck -C` and it will create an hourly scheduled task to check that the logs are working correctly.

**Comment by willat8** [comment]
Thanks @seud0nym, I will upgrade.

**Comment by willat8** [comment]
This has come back even on 0432 on both my DJA0230s. Am just going to leave `log` and `lsyslogd` disabled and not worry about it.
