### ISSUE TITLE
Firmware version different after importing config file

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#72]
I imported a config file from bricked DJA0231 which was running 20.3.c.0389-MR19-RA and it's returning the same firmware version on the destination DJA0231 which had vcnt-a_20.3.c.0389-MR20-RA installed.

This is from SSH on my current DJA0231.

```
Product: vcnt-a_telstra
Release: Egyptian Blue (20.3.c)
Version: 20.3.c.0389-3241005-20211107230250-1d419907a0533ea736114d0b54c3001bc9cc2130
```

This is from GUI on my current DJA0231

<img width="251" alt="image" src="https://user-images.githubusercontent.com/49738152/154181965-ea46e59e-b0de-4fb2-a4ed-6f6b5fa12a01.png">

**Comment by seud0nym** [comment]
> spare DJA0231 running 20.3.c.0389-MR19-RA

Do you mean 20.3.c.03**2**9-MR19-RA?

The suffix is defined in the `/etc/config/versioncusto` configuration file, which is why the configuration import changes it. You can just edit it manually back to the correct suffix.

**Comment by gyCfjSnO** [comment]
> > spare DJA0231 running 20.3.c.0389-MR19-RA
> 
> Do you mean 20.3.c.03**2**9-MR19-RA?
> 
> The suffix is defined in the `/etc/config/versioncusto` configuration file, which is why the configuration import changes it. You can just edit it manually back to the correct suffix.

Sorry I meant bricked not spare.

**Comment by seud0nym** [comment]
I don't use configuration export/import any more because of its habit of doing stuff like this. 

I use `./mtd-backup -colvy0` to make a full backup of the mtd partitions and current configuration. Then I use `./reset-to-factory-defaults -f new.rbi --restore-config` which does a complete recovery of configuration, installed/removed packages and `de-telstra`/`tch-gui-unhide` settings. 

The bonus is that if anything goes wrong with the upgrade, I can also completely restore the device to its exact state using `./mtd-restore`.
