### ISSUE TITLE
Cosmetic issues with classic theme

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#77]
I love the classic theme in 2022.03.01. I've noticed some minor visual inconsistencies

* Bigger margin on the right side compared to the left side. Especially noticeable on mobile
  ![image](https://user-images.githubusercontent.com/2316013/156158624-4db4f124-6749-487a-b8d9-1e189a5c84b4.png)

* The header is different on home.lp
  ![image](https://user-images.githubusercontent.com/2316013/156158874-f42ad8f8-44b1-4b35-b950-1aa02f4dce4f.png)
  vs gateway.lp
  ![image](https://user-images.githubusercontent.com/2316013/156158936-16183b44-fd7b-463c-9750-ae30c2e65315.png)

**Comment by seud0nym** [comment]
> * Bigger margin on the right side compared to the left side. Especially noticeable on mobile

That is not actually just the Classic theme - it is part of the base Telstra style sheet. It does it on all themes and the stock GUI. Anyway, it is fixed for the next release.

> * The header is different on home.lp

How do you mean "different"? It is the same logo (from the light theme), but it looks different because it is on the black background. Is that what you mean?

The other issue is that the stock GUI doesn't actually have a logo on the Basic view. So, I could just remove it completely...

Or, I could use the logo from the night theme, like this:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/41851175/156294008-9486b840-f5f0-42c2-b264-7a6561552089.png">

**Comment by seud0nym** [comment]
That is the stock GUI experience.

Do you think the Basic view should scroll, or the Advanced view should be fixed?

**Comment by willat8** [comment]
I had a play with the DOM inspector and copied the header and its container from the Advanced view into the Basic view

![image](https://user-images.githubusercontent.com/2316013/156859037-fca0b2fb-633a-424a-8ed4-4dad6d4f5181.png)

**Comment by seud0nym** [comment]
I have pushed up an interim release with these fixes that you can download with:
```
./tch-gui-unhide -u
```

**Comment by willat8** [comment]
Wow - that looks perfect to me. Big thanks.
