### ISSUE TITLE
UPnP Active Rules

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#81]
How can I clear out old UPnP Active Rules? The app that was used on my TV to open them has since been deleted (and actually TV factory reset) so I know it isn't dormant or anything. Relates to IP ending in 90.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/49738152/162642448-cb8d34dc-d5ae-45c6-82bb-0b1182a4f53a.png">

**Comment by seud0nym** [comment]
Looking at `/etc/config/upnpd`, it seems the leases are in `/var/upnp.leases`. /var == /tmp, so a reboot should clear them. Alternatively, you could try:
```
/etc/init.d/miniupnpd-tch stop
rm /var/upnp.leases
/etc/init.d/miniupnpd-tch start
```
The one you want to keep should just re-register, I think.

Instead of deleting the lease file, you could probably edit it and remove them.

I had a look at the transformer mapping file, and it isn't possible just to enable deleting in that table. There is no support at the back end for it.

If you try the file delete route and it works, I could probably easily add something to remove the leases from the screen.

**Comment by gyCfjSnO** [comment]
Thanks running that command fixed it :)

**Comment by seud0nym** [comment]
Added button in new release to clear all leases.
